name: "CI"

on:
  push:
    branches:
      - "*"
    tags:
      - "*"
  pull_request:
    branches:
      - "develop"
  workflow_dispatch:

jobs:
  build:
    name: "CI - Build Job"
    runs-on: "ubuntu-20.04"

    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v2"

      - name: "Install Ubuntu Packages"
        run: "sudo apt-get update && sudo apt-get -y install scons texlive-latex-extra"

      - name: "Build with SCons"
        run: "scons"

      - name: "Create GitHub Release"
        id: "create_github_release"
        if: "${{ startsWith(github.ref, 'refs/tags/') }}"
        uses: "actions/create-release@v1"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          tag_name: "${{ github.ref }}"

      - name: "Upload Slides to GitHub Release"
        if: "${{ startsWith(github.ref, 'refs/tags/') }}"
        uses: "actions/upload-release-asset@v1"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          asset_content_type: "application/pdf"
          asset_name: "talk.pdf"
          asset_path: "tex/talk.pdf"
          upload_url: "${{ steps.create_github_release.outputs.upload_url }}"

      - name: "Upload Handout to GitHub Release"
        if: "${{ startsWith(github.ref, 'refs/tags/') }}"
        uses: "actions/upload-release-asset@v1"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          asset_content_type: "application/pdf"
          asset_name: "handout.pdf"
          asset_path: "tex/handout.pdf"
          upload_url: "${{ steps.create_github_release.outputs.upload_url }}"
